# AmongMiners Multiarena / Multiverse System
AmongMiners:
  # Do not change this value:
  config: 1
  
  # Do you want the arena to be enabled?
  enabled: false
  # Minimum amount of players required for the game to start.
  MinPlayers: 4
  # Maximum amount of players being able to join.
  MaxPlayers: 10
  # From here on, you can create the join signs:
  JoinSigns:
    # Do you want joinsigns to be enabled? (Support for Multiworld servers only!)
    enabled: false
    # Syntax: "WORLD;X-coordinate;Y-coordinate;Z-coordinate" | Example: "world;127;64;-25"
    # (If no Fallback is provided, players will be kicked when the game ends.)
    Locations:
#      - "world;0;64;0"
#      - "world;0;64;1"
#      - "world;0;64;2"
  # Lobby Location where players wait for the game to start:
  LobbyLocation:
    World: "world"
    X: 0
    Y: 64
    Z: 0
  # Where do you want players to be teleported to when the game is over or when they quit the current game/ lobby?
  Fallback:
    Bungeecord:
      enabled: false
      Server: "lobbyserver"
    Multiworld:
      enabled: false
      World: "lobbyworld"
